ctblog/blog/urls.py
from django.urls import path
from .views import home_page, contact_us, blog_detail, about_us
app_name = "blog"
urlpatterns = [
    path('',home_page, name = "home"),
    path('contact-us/',contact_us, name= "contact-us"),
    path('about-us/',about_us, name= "about-us"),
    path('blog-detail/<int:pk>/',blog_detail, name="blog-detail")
]

ctblog/ctblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls') ),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ctblog/blog/models.py
from django.db import models

# Create your models here.


class Blog (models.Model):

    title = models.CharField(max_length = 255)
    description = models.TextField()
    image = models.ImageField(upload_to = "blog_posts/", default = None, null = True, blank = True)
    def _str_(self):
        return self.title
    


class Contact (models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now = True)
    

    def _str_(self):
        return self.first_name + "-"+self.last_name
    


class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name = "blog_comment",on_delete = models.CASCADE )
    name = models.CharField(max_length=255)
    message = models.TextField()

    def _str_(self):
        return self.blog.title + "-"+self.message

ctblog/blog/forms.py
from  django import forms
from .models import Contact, Comment

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = "__all__"


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ["blog"]

ctblog/blog/views.py
from django.shortcuts import render, HttpResponse
from .models import Blog, Contact, Comment
from .forms import ContactForm, CommentForm
# Create your views here.
def home_page (request):
    context = {}
    blogs = Blog.objects.all()
    context["blogs"] = blogs

    return render(request, "home.html", context)

def about_us (request):
    context = {}

    return render(request, "about_us.html", context)
  
def contact_us (request):
     context = {}
     if request.POST:
          my_form = ContactForm(request.POST)
          if my_form.is_valid():
               my_form.save()
          else :
               context["errors"]= my_form.errors


     return render(request, "contact_us.html", context)


def blog_detail (request, pk):
     context={}
     blog = Blog.objects.get(id = pk)
     context['blog'] = blog

     if request.POST:
          comment_form = CommentForm(request.POST)
          if comment_form.is_valid():
               obj = comment_form.save(commit = False)
               obj.blog = context["blog"]
               obj.save()
          else:
               context["errors"] = comment_form.errors
     comments = Comment.objects.filter(blog = context['blog'])
     context['comments'] = comments
     return  render (request, "blog_details.html", context)

ctblog/blog/templates/about_us.html
{%extends  'base.html'%}


{%block content%}

{%if errors%}
{{errors}}
{%endif%}
<div >
   <p>

      What is Lorem Ipsum?
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
      
      Why do we use it?
      It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
      
      
      Where does it come from?
      Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
      
      The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
</div>
{%endblock%}

ctblog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {%load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
    <link rel = "stylesheet" href = "{%static 'style.css'%}"">
  
</head>
<body>
    <header>
        <nav>
            <ul class = "nav">
                <li><a href = "{%url 'blog:home'%}">Home page</a></li>
                <li><a href = "{%url 'blog:contact-us'%}">Contact us</a></li>
                <li><a href = "{%url 'blog:about-us'%}" >About us</a></li>
            </ul>
        </nav>
    </header>
    <br>
   {%block content%}

   {%endblock%}

   

   <footer>
    <div class="footer">
        
    <div class="row">
    <ul>
    <li><a href = "{%url 'blog:home'%}">Home page</a></li>
    <li><a href = "{%url 'blog:contact-us'%}">Contact us</a></li>
    <li><a href = "{%url 'blog:about-us'%}" >About us</a></li>
    </ul>
    </div>
    
    <div class="row">
       Copyright © 2023  - All rights reserved || Designed By: Astghik Tonoyan 
    </div>
    </div>
    </footer>


   <script src = "{%static 'js/main.js'%}"></script>
</body>
</html>

ctblog/blog/templates/blog_details.html
{%extends  'base.html'%}


{%block content%}
<div class = "divblog">
<h1>{{blog.title}}</h1>
{%if blog.image%}
<div class = "divblog">
<img width = "300px" src = "{{blog.image.url}}" alt  = "">
</div>
{%endif%}
<p>{{blog.description}}</p>

<hr>
<h3>Comments</h3>
{%for comment in comments%}
<p><b>{{comment.name}}</b></p>
<p>{{comment.message}}</p>
<hr>
</div>
{%endfor%}


{%if errors%}
{{errors}}
{%endif%}
<form method = "POST" action = "">{%csrf_token%}
    <label for = "">Name</label>
    <br>
    <input type = "text" name = "name">
    <br>
    <label for = "">Message</label>
    <br>
    <textarea name="message" id = "" cols = "30" rows = "10"> </textarea>
    <br>
 
    <button class = "submit" >Submit</button>
 


    {%endblock%}

ctblog/blog/templates/contact_us.html
{%extends  'base.html'%}


{%block content%}

{%if errors%}
{{errors}}
{%endif%}
<div class = "contact">
   <h1 >Contact</h1>
 
</div>
<hr>
<div class = "contact">
   
  
<form  class = "form" method = "post" action = "">{%csrf_token%}
   <label for = "">First Name</label>
   <br>
   <input  type = "text" name = "first_name">
   <br>

   <label for = "">Last Name</label>
   <br>
   <input type = "text" name = "last_name">
   <br>

   <label for = "">Email</label>
   <br>
   <input type = "email" name = "email">
   <br>

   <label for = "">Message</label>
   <br>
   <textarea name="message" id = "" cols = "30" rows = "10"> </textarea>
   <br>

   <button class = "submit">Submit</button>


</form>
</div>
{%endblock%}

ctblog/blog/templates/home.html
{%extends  'base.html'%}


{%block content%}
<div class = "divblog">
<h1><b>BUSINESS SECRETS BLOG</b></h1>

{%for blog in blogs%}
{%if blog.image%}
<img width = "250px" src = "{{blog.image.url}}" alt  = "">
{%endif%}
<p><a href = "{%url 'blog:blog-detail' pk=blog.id %}">{{blog.title}}</a></p>

<hr>
</div>
{%endfor%}

{%endblock%}